# Generated by Django 4.2.30 on 2026-06-17 05:55

from django.db import migrations, models


def convert_staff_to_pharmacist(apps, schema_editor):
    CustomUser = apps.get_model('accounts', 'CustomUser')
    CustomUser.objects.filter(role='staff').update(role='pharmacist')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_avatar'),
    ]

    operations = [
        migrations.RunPython(convert_staff_to_pharmacist, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('pharmacist', 'Pharmacist')], default='pharmacist', max_length=20),
        ),
    ]
